### PR TITLE
Pretagovc

### PR DESCRIPTION
**Pull request by ivanteoh**
Bug fixes:
- Scheduler filter to send only to a channel option.
- Made the last_trigger for the timed scheduler only record when there are newsletters sent.

### CODE REVIEW

**Comment by ivanteoh** [comment]
@WouterVH Can we merge these changes to master? Thank you.

**Comment by ivanteoh** [comment]
@WouterVH Follow with the status. Or allow us to merge to master branch? Thank you.

**Comment by frisi** [comment]
@ivanteoh maybe @saily or @dnouri can (/ want to) take a look at this

**Comment by saily** [comment]
Can you please resolve the conflicts/rebase onto master first?

**Comment by ivanteoh** [comment]
Sorry about that. I thought I already rebase the branch. I will back to this ticket later. I am busy with something else at the moment.

**Comment by ivanteoh** [comment]
@saily sorry about long delay. The conflict is on the `docs/HISTORY.txt`. I have to add the history notes first in Master branch to avoid conflict. Now it is safe to merge. The only changes are in `scheduler.py. The rest are rebasing from master. What do you think?

**Comment by saily** [comment]
@ivanteoh ok, better would have been to rebase your branch, but for me it's ok to merge. You just should update the changelog, because you did a lot of cleanup flake8, changelog as well. this should also be mentioned there.

**Comment by ivanteoh** [comment]
@saily Really want to apologize about this merge. It is a mess. The cleanup is done by @WouterVH By the way, I added the history note on cleanup flake8, changelog. Thank you.

**Pull request merged**
